services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env.development
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.development
    develop:
      watch:
        - action: sync
          path: .
          target: /app
